import type { NextApiRequest, NextApiResponse } from 'next';
import axios from 'axios';
import { Groq } from 'groq-sdk';

// Initialize Groq client
function getGroqClient() {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is required. Add it in Vercel environment variables.');
  }
  return new Groq({ apiKey });
}

// Improved JSON parsing with error handling
function safeParseJSON(content: string) {
  console.log('🔄 Attempting to parse JSON, length:', content.length);
  
  let cleaned = content.trim();
  
  // Remove markdown code blocks
  if (cleaned.startsWith('```json')) cleaned = cleaned.substring(7);
  if (cleaned.startsWith('```')) cleaned = cleaned.substring(3);
  if (cleaned.endsWith('```')) cleaned = cleaned.substring(0, cleaned.length - 3);
  
  // Extract JSON between first { and last }
  const jsonStart = cleaned.indexOf('{');
  const jsonEnd = cleaned.lastIndexOf('}') + 1;
  
  if (jsonStart !== -1 && jsonEnd > jsonStart) {
    cleaned = cleaned.substring(jsonStart, jsonEnd);
  }
  
  try {
    const parsed = JSON.parse(cleaned);
    console.log('✅ JSON parsed successfully');
    return parsed;
  } catch (parseError: any) {
    console.error('❌ JSON parse error:', parseError.message);
    
    // Try to fix common issues
    try {
      const fixed = cleaned
        .replace(/,\s*}/g, '}')
        .replace(/,\s*]/g, ']')
        .replace(/'/g, '"')
        .replace(/:\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*([,}])/g, ':"$1"$2');
      
      const reparsed = JSON.parse(fixed);
      console.log('✅ JSON re-parsed after fixing');
      return reparsed;
    } catch (e) {
      console.error('❌ Still cannot parse JSON, using fallback');
      return getFallbackResponse(cleaned.substring(0, 100));
    }
  }
}

function getFallbackResponse(queryHint: string) {
  return {
    playerInfo: null,
    teamInfo: null,
    worldCupInfo: null,
    analysis: "Analysis generated by AI",
    videoSearchTerm: "football highlights 2024",
    confidenceScore: 0.5
  };
}

// Enhanced prompt with detailed information
async function analyzeFootballQuery(query: string) {
  console.log('🤖 Starting AI analysis for:', query);
  const groq = getGroqClient();
  
  const prompt = `You are FutbolAI, an expert football analyst with comprehensive knowledge.

Analyze: "${query}"

Return ONLY JSON in this structure:

FOR PLAYERS:
{
  "playerInfo": {
    "name": "Full name",
    "fullName": "Complete name",
    "dateOfBirth": "YYYY-MM-DD",
    "age": "Current age",
    "nationality": "Nationality",
    "height": "Height in cm",
    "weight": "Weight in kg",
    "preferredFoot": "Left/Right/Both",
    
    "position": "Primary position",
    "positions": ["Primary", "Secondary positions"],
    "playingStyle": "Description of playing style",
    
    "currentClub": "Current club",
    "clubNumber": "Squad number",
    "marketValue": "Estimated value with currency",
    
    "careerStats": {
      "club": {
        "totalGoals": "Number",
        "totalAssists": "Number", 
        "totalAppearances": "Number",
        "goalsPerMatch": "Ratio"
      },
      "international": {
        "caps": "Number of appearances",
        "goals": "Number of goals",
        "debut": "Date of international debut"
      }
    },
    
    "clubCareer": [
      {"club": "Club name", "period": "Years", "appearances": "Number", "goals": "Number"}
    ],
    
    "internationalCareer": {
      "nationalTeam": "Country",
      "tournamentAppearances": [
        {"tournament": "World Cup 2022", "apps": "Number", "goals": "Number"}
      ]
    },
    
    "individualAwards": ["Ballon d'Or (years)", "Other awards"],
    "teamHonors": [
      {"competition": "Champions League", "wins": "Number", "years": [2022, 2018]},
      {"competition": "League Title", "wins": "Number", "years": [2023, 2022]}
    ],
    
    "currentSeason": {
      "clubAppearances": "Number",
      "clubGoals": "Number",
      "clubAssists": "Number"
    }
  },
  "teamInfo": null,
  "worldCupInfo": null,
  "analysis": "Detailed analysis including career highlights, playing style, and current form.",
  "videoSearchTerm": "[Player Name] 2024 highlights goals skills recent matches",
  "confidenceScore": 0.95
}

FOR CLUB TEAMS (like Real Madrid, Barcelona, Manchester City):
{
  "playerInfo": null,
  "teamInfo": {
    "name": "Full club name",
    "nicknames": ["Nicknames"],
    "type": "club",
    "founded": "Year founded",
    "location": {
      "city": "City",
      "country": "Country"
    },
    
    "stadium": {
      "name": "Stadium name",
      "capacity": "Seating capacity",
      "opened": "Year opened"
    },
    
    "currentManager": {
      "name": "Manager name (CURRENT - October 2024)",
      "nationality": "Manager nationality",
      "appointed": "Date appointed"
    },
    
    "league": "Current league",
    
    "trophies": {
      "domestic": [
        {"competition": "La Liga", "wins": "Exact number (e.g., 35)", "icon": "🏆"},
        {"competition": "Copa del Rey", "wins": "Exact number (e.g., 20)", "icon": "🥇"},
        {"competition": "Supercopa de España", "wins": "Exact number", "icon": "🏅"}
      ],
      "continental": [
        {"competition": "UEFA Champions League", "wins": "Exact number (e.g., 14)", "icon": "⭐"},
        {"competition": "Europa League", "wins": "Exact number", "icon": "🌟"}
      ],
      "worldwide": [
        {"competition": "FIFA Club World Cup", "wins": "Exact number", "icon": "🌍"}
      ]
    },
    
    "currentSquad": {
      "keyPlayers": [
        {"name": "Player name", "position": "Position", "nationality": "Country"}
      ],
      "captain": "Captain name"
    },
    
    "mainRivalries": ["El Clásico (vs Barcelona)", "Other rivalries"],
    "clubValue": "Estimated club value",
    
    "currentSeason": {
      "leaguePosition": "Current position",
      "matchesPlayed": "Number",
      "wins": "Number",
      "draws": "Number",
      "losses": "Number"
    }
  },
  "worldCupInfo": null,
  "analysis": "Detailed analysis including history, current season performance, trophy cabinet, and key players.",
  "videoSearchTerm": "[Team Name] 2024 highlights goals recent matches full games",
  "confidenceScore": 0.95
}

FOR NATIONAL TEAMS (like Spain, Brazil, Argentina):
{
  "playerInfo": null,
  "teamInfo": {
    "name": "Country name",
    "nicknames": ["La Roja", "Other nicknames"],
    "type": "national",
    "fifaCode": "FIFA code",
    "fifaRanking": "Current FIFA ranking position",
    "confederation": "UEFA/CONMEBOL/etc",
    
    "currentCoach": {
      "name": "Coach name (CURRENT - October 2024)",
      "nationality": "Coach nationality",
      "appointed": "Date appointed"
    },
    
    "homeStadium": "Main home stadium",
    
    "majorHonors": [
      {"competition": "FIFA World Cup", "titles": "Number of titles", "years": [2010, ...], "icon": "🏆"},
      {"competition": "UEFA European Championship", "titles": "Number", "years": [2008, 2012], "icon": "🇪🇺"},
      {"competition": "Copa América", "titles": "Number", "years": [...], "icon": "🇦🇷"}
    ],
    
    "records": {
      "mostCaps": {"player": "Player name", "caps": "Number"},
      "topScorer": {"player": "Player name", "goals": "Number"}
    },
    
    "currentSquad": {
      "captain": "Captain name",
      "keyPlayers": [
        {"name": "Player name", "position": "Position", "club": "Current club"}
      ]
    },
    
    "mainRivalries": ["vs Portugal", "vs France", "vs Italy"],
    "playingStyle": "Traditional playing style description"
  },
  "worldCupInfo": null,
  "analysis": "Detailed analysis including history, playing style, current squad, and tournament expectations.",
  "videoSearchTerm": "[Country Name] national team 2024 highlights matches goals",
  "confidenceScore": 0.95
}

FOR WORLD CUP:
{
  "playerInfo": null,
  "teamInfo": null,
  "worldCupInfo": {
    "year": 2026,
    "edition": "23rd FIFA World Cup",
    "host": "USA, Canada, Mexico",
    "hostCities": ["List of host cities"],
    "qualifiedTeams": ["USA", "Canada", "Mexico", "Argentina", "France", "Brazil"],
    "venues": ["List stadiums"],
    "defendingChampion": "Argentina",
    "mostTitles": {"country": "Brazil", "titles": 5}
  },
  "analysis": "Detailed analysis of the upcoming World Cup including format, favorites, and key information.",
  "videoSearchTerm": "World Cup 2026 highlights preview qualifiers",
  "confidenceScore": 0.95
}

IMPORTANT:
1. Use EXACT numbers for trophies (e.g., "14" not "fourteen")
2. For managers/coaches, use CURRENT information (October 2024)
3. Include Copa del Rey for Spanish clubs
4. Add trophy icons where specified
5. Make videoSearchTerm specific and searchable

Return ONLY the JSON object, no other text.`;

  try {
    console.log('🚀 Calling Groq with enhanced prompt');
    const completion = await groq.chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.3,
      max_tokens: 2000,
    });

    const content = completion.choices[0]?.message?.content || '{}';
    console.log('📄 Raw AI response received');
    
    const parsed = safeParseJSON(content);
    
    // Ensure required fields
    if (!parsed.analysis) parsed.analysis = `Comprehensive analysis of ${query}`;
    if (!parsed.videoSearchTerm) parsed.videoSearchTerm = `${query} football highlights 2024`;
    if (!parsed.confidenceScore) parsed.confidenceScore = 0.8;
    
    return parsed;
    
  } catch (error: any) {
    console.error('❌ Groq API error:', error.message);
    return getFallbackResponse(query);
  }
}

// Enhanced YouTube search with better error handling
async function searchYouTube(searchTerm: string) {
  console.log('🎬 Searching YouTube for:', searchTerm);
  
  try {
    const apiKey = process.env.YOUTUBE_API_KEY;
    
    if (!apiKey) {
      console.warn('⚠️ YouTube API key not set');
      // Try a public search fallback
      return getPublicYouTubeFallback(searchTerm);
    }

    // Clean and optimize search term
    const cleanTerm = searchTerm
      .replace(/\[.*?\]/g, '') // Remove brackets
      .replace(/\s+/g, ' ')    // Normalize spaces
      .trim();
    
    const query = `${cleanTerm} football 2024`;
    console.log('🔍 Optimized YouTube query:', query);
    
    const response = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: {
        part: 'snippet',
        q: query,
        type: 'video',
        maxResults: 3,
        key: apiKey,
        videoEmbeddable: 'true',
        safeSearch: 'none', // Changed from 'strict' to 'none' for more results
        order: 'viewCount', // Most viewed videos first
        videoDuration: 'any',
        relevanceLanguage: 'en',
      },
      timeout: 5000, // 5 second timeout
    });

    console.log('📊 YouTube API response:', {
      status: response.status,
      items: response.data.items?.length || 0
    });
    
    if (response.data.items?.length > 0) {
      // Pick the first result (most viewed)
      const videoId = response.data.items[0].id.videoId;
      const videoUrl = `https://www.youtube.com/embed/${videoId}`;
      console.log('✅ YouTube video found:', videoUrl);
      return videoUrl;
    } else {
      console.warn('📭 No YouTube videos found, using fallback');
      return getPublicYouTubeFallback(searchTerm);
    }
  } catch (error: any) {
    console.error('❌ YouTube search error:', {
      message: error.message,
      code: error.code,
      status: error.response?.status
    });
    
    return getPublicYouTubeFallback(searchTerm);
  }
}

// Public YouTube fallback (no API key needed for specific videos)
function getPublicYouTubeFallback(searchTerm: string) {
  const term = searchTerm.toLowerCase();
  
  // Curated high-quality football highlights
  const publicVideos: Record<string, string> = {
    // Clubs
    'real madrid': 'XfyZ6EueJx8',
    'barcelona': '3X7XG5KZiUY',
    'manchester city': 'KXwHEvDE2-U',
    'liverpool': '6MfLJBHjK0k',
    'bayern': 'HfQmI1Q5LQc',
    'psg': '8CjDcFyF2l0',
    'juventus': 'Uf4nVHLLqPA',
    'ac milan': 'V7GqQN5Dm1k',
    'inter milan': 'dZqkf1ZnQh4',
    'chelsea': 'dZqkf1ZnQh4',
    'arsenal': 'dZqkf1ZnQh4',
    'manchester united': 'dZqkf1ZnQh4',
    
    // National Teams
    'spain': 'eJXWcJeGXlM',
    'brazil': 'eJXWcJeGXlM',
    'argentina': 'eJXWcJeGXlM',
    'france': 'J8LcQOHtQKs',
    'germany': 'dZqkf1ZnQh4',
    'italy': 'dZqkf1ZnQh4',
    'england': 'dZqkf1ZnQh4',
    'portugal': 'dZqkf1ZnQh4',
    'netherlands': 'dZqkf1ZnQh4',
    'belgium': 'dZqkf1ZnQh4',
    'colombia': 'dZqkf1ZnQh4',
    
    // Players
    'ronaldo': 'OUKGsb8CpF8',
    'messi': 'ZO0d8r_2qGI',
    'mbappe': 'RdGpDPLT5Q4',
    'haaland': '4XqQpQ8KZg4',
    'neymar': 'FIYzK8PSLpA',
    'benzema': '6kl7AOKVpCM',
    'modric': 'dZqkf1ZnQh4',
    'kroos': 'dZqkf1ZnQh4',
    'vinicius': 'dZqkf1ZnQh4',
    'bellingham': 'dZqkf1ZnQh4',
    
    // World Cup
    'world cup': 'dZqkf1ZnQh4',
  };

  for (const [key, videoId] of Object.entries(publicVideos)) {
    if (term.includes(key)) {
      console.log('🔄 Using public fallback for:', key);
      return `https://www.youtube.com/embed/${videoId}`;
    }
  }

  // Default to a popular football highlights channel
  console.log('🔄 Using default football highlights');
  return 'https://www.youtube.com/embed/dZqkf1ZnQh4';
}

// Main API handler
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  const { action, query } = req.query;

  if (action === 'search' && query && typeof query === 'string') {
    console.log(`\n=== NEW REQUEST: "${query}" ===`);
    
    try {
      // Try AI analysis
      const aiAnalysis = await analyzeFootballQuery(query);
      console.log('✅ AI Analysis completed, type:', 
        aiAnalysis.playerInfo ? 'player' : 
        aiAnalysis.teamInfo ? 'team' : 
        aiAnalysis.worldCupInfo ? 'worldCup' : 'general'
      );
      
      const searchTerm = aiAnalysis.videoSearchTerm || query;
      console.log('🎯 YouTube search term:', searchTerm);
      
      const youtubeUrl = await searchYouTube(searchTerm);
      console.log('✅ Final YouTube URL:', youtubeUrl);
      
      const response = {
        success: true,
        query: query,
        timestamp: new Date().toISOString(),
        type: aiAnalysis.playerInfo ? 'player' : 
              aiAnalysis.teamInfo ? 'team' : 
              aiAnalysis.worldCupInfo ? 'worldCup' : 'general',
        data: aiAnalysis.playerInfo || aiAnalysis.teamInfo || aiAnalysis.worldCupInfo || null,
        playerInfo: aiAnalysis.playerInfo || null,
        teamInfo: aiAnalysis.teamInfo || null,
        worldCupInfo: aiAnalysis.worldCupInfo || null,
        youtubeUrl: youtubeUrl,
        analysis: aiAnalysis.analysis || `Comprehensive analysis of ${query}`,
        confidence: aiAnalysis.confidenceScore || 0.8,
        source: 'Groq AI',
        debug: 'AI_SUCCESS'
      };

      return res.status(200).json(response);
      
    } catch (error: any) {
      console.error('❌ API error:', error.message);
      
      return res.status(200).json({
        success: false,
        query: query,
        type: 'error',
        error: 'Service temporarily unavailable',
        timestamp: new Date().toISOString(),
        youtubeUrl: getPublicYouTubeFallback(query),
        analysis: `Please try your search again in a moment.`,
        debug: 'SERVICE_ERROR'
      });
    }
  }

  // API docs
  res.status(200).json({
    message: 'FutbolAI Enhanced API is running! 🏆',
    version: '3.0',
    features: 'Detailed football analytics with trophy counts, current managers, and enhanced data',
    endpoints: {
      search: 'GET /api/ai?action=search&query=your-query',
      examples: [
        '/api/ai?action=search&query=Real%20Madrid',
        '/api/ai?action=search&query=Spain%20national%20team',
        '/api/ai?action=search&query=Cristiano%20Ronaldo',
        '/api/ai?action=search&query=World%20Cup%202026'
      ]
    }
  });
}